name: CI - dev
on: 
  push:
  pull_request:

jobs:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      NODE_AUTH_TOKEN: ${{ secrets.ADMIN_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '11'

      - name: Install
        run: npm i