name: Hello world
on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      NODE_AUTH_TOKEN: ${{ secrets.ADMIN_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: npm i

      - name: build
        run: npm run build